baseURL = "https://axjms1.github.io/maker_portfolio/"
copyright = "© Jason Sandidge 2023"
languageCode = "en-us"
paginate = 50
title = "Maker Portfolio"
timezone = "America/Denver"
[[module.imports]]
path = "github.com/willfaught/paige"

enableInlineShortcodes = true

[params.authors.JS]
name = "Jason Sandidge"

[paige.search]
hide_page = false

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[paige.menu]
breakpoint = "sm" # Bootstrap breakpoint at which to display all menu items
style = "pills" # Must be "links", "pills", "tabs", or "underline"


[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "overview"
name = "Overview"
url = "/Overview/"
style = "pills"
weight = 20

[[languages.en.menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "Scratch"
name = "Scratch"
parent = "projects"
url = "/projects/scratch/"
weight = 10

[[languages.en.menu.main]]
identifier = "Makey-Makey"
name = "Makey-Makey"
parent = "projects"
url = "/projects/makey-makey/"
weight = 20

[[languages.en.menu.main]]
identifier = "proposal"
name = "Proposal"
url = "/proposal/"
weight = 40

[[languages.en.menu.main]]
identifier = "resources"
name = "Resources"
url = "/resources/"
weight = 50

[[languages.en.menu.main]]
identifier = "future"
name = "Future"
url = "/future/"
weight = 60

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 70

[outputs]
home = ["html", "json", "rss"]

[taxonomies]
tag = "tags"